# Generated by Django 5.2.3 on 2025-06-20 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftq',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ftqs', to='quizzes.quiz'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='quizzes.quiz'),
        ),
    ]
