# Generated by Django 5.2.3 on 2025-06-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_ftq_quiz_mcq_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='points',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
