# Generated by Django 5.2.3 on 2025-06-28 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_choice_is_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quizzes.attempt'),
        ),
    ]
